'0':
  application_path: C:/Users/m3t3r/AppData/Local/Programs/balena-etcher/balenaEtcher.exe
'1':
  application_path: C:/Users/m3t3r/Downloads/parsec-windows.exe
'10':
  application_path: C:/Users/m3t3r/Downloads/PrismLauncher-Windows-MSVC-Setup-7.1.exe
'11':
  application_path: C:/Users/m3t3r/Downloads/Obsidian.1.0.3.exe
'2':
  application_path: C:/Users/m3t3r/Downloads/Motrix-1.8.19-x64.exe
'3':
  application_path: C:/Users/m3t3r/Downloads/WinSCP-6.1.1-Setup.exe
'4':
  application_path: C:/Users/m3t3r/Desktop/Godot_4.1.exe
'5':
  application_path: C:/Users/m3t3r/AppData/Local/Programs/Notion/Notion.exe
'6':
  application_path: C:/Users/m3t3r/AppData/Local/Programs/mybsmart/MybSmart.exe
'7':
  application_path: C:/Users/m3t3r/Desktop/Tor Browser/Browser/firefox.exe
'8':
  application_path: C:/Program Files/VirtualDJ/virtualdj.exe
'9':
  application_path: C:/Users/m3t3r/Desktop/The.Witness.v24.01.2019/The.Witness.v24.01.2019/witness64_d3d11.exe
